### PR TITLE
Export reconciler Validate method

### LINKED ISSUE #578: Validate reconcilers at test-time w/ helpful error messages
When a (sub)reconciler is invalid, because, say, it missing `ChildObjectManager`, then its (sub)reconciler test suite fails with a panic. Tracing the panic back to the missing `ChildObjectManager` is possible but tedious. 

```
❯ go test ./controllers -v -run TestApplyServiceBindingSecret
=== RUN   TestApplyServiceBindingSecret
=== RUN   TestApplyServiceBindingSecret/creates_service_binding_secret_with_config_properties
--- FAIL: TestApplyServiceBindingSecret (0.00s)
    --- FAIL: TestApplyServiceBindingSecret/creates_service_binding_secret_with_config_properties (0.00s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x4ec7ce2]

goroutine 70 [running]:
testing.tRunner.func1.2({0x5418380, 0x661f600})
        /usr/local/Cellar/go/1.23.5/libexec/src/testing/testing.go:1632 +0x230
testing.tRunner.func1()
        /usr/local/Cellar/go/1.23.5/libexec/src/testing/testing.go:1635 +0x35e
panic({0x5418380?, 0x661f600?})
        /usr/local/Cellar/go/1.23.5/libexec/src/runtime/panic.go:785 +0x132
reconciler.io/runtime/reconcilers.(*ChildReconciler[...]).reconcile(0x5701040, {0x56e4490, 0xc000137b30}, 0xc00002c1a0)
        /Users/*****/workspace/reconcilerio-runtime/reconcilers/child.go:314 +0x582
reconciler.io/runtime/reconcilers.(*ChildReconciler[...]).Reconcile(0x5701040, {0x56e4490, 0xc000137ad0}, 0xc00002c1a0)
        /Users/*****/workspace/reconcilerio-runtime/reconcilers/child.go:229 +0x4f2
reconciler.io/runtime/reconcilers.(*Advice[...]).init.func1.2(0x5418b00?, {0x56cbd60?, 0xc000285810?})
        /Users/*****/workspace/reconcilerio-runtime/reconcilers/advice.go:92 +0x34
reconciler.io/runtime/reconcilers.(*Advice[...]).Reconcile(0x55baf80, {0x56e4490?, 0xc00002a6f0}, 0xc00002c1a0)
        /Users/*****/workspace/reconcilerio-runtime/reconcilers/advice.go:150 +0x19e
reconciler.io/runtime/testing.(*SubReconcilerTestCase[...]).Run.func3(0x56e4490?, {0x56cbd88?, 0xc00050ebe0?}, 0xc000582c40?, {0x56e4490?, 0xc00002a6f0?}, 0x0?)
        /Users/*****/workspace/reconcilerio-runtime/testing/subreconciler.go:287 +0x9b
reconciler.io/runtime/testing.(*SubReconcilerTestCase[...]).Run(0x56eea40, 0xc0002ab040, 0xc000284af0, 0x56bbaf8)
        /Users/*****/workspace/reconcilerio-runtime/testing/subreconciler.go:288 +0x15d2
reconciler.io/runtime/testing.SubReconcilerTestSuite[...].Run.func1()
        /Users/*****/workspace/reconcilerio-runtime/testing/subreconciler.go:349 +0x5f
testing.tRunner(0xc0002ab040, 0xc000453e60)
        /usr/local/Cellar/go/1.23.5/libexec/src/testing/testing.go:1690 +0xf4
created by testing.(*T).Run in goroutine 69
        /usr/local/Cellar/go/1.23.5/libexec/src/testing/testing.go:1743 +0x390
FAIL    ***************/controller/controllers  1.009s
FAIL
```

It would be nice if invalid (sub)reconcilers would be reported with the same error message one sees when running the controller.

Since `validate` is not exported it's not easy for reconciler authors to validate their reconcilers in their tests.

### PR DESCRIPTION
**Pull request by scothis**
Export the Validate() method for Reconcilers and SubReconcilers. Test cases detect this method and call it before the test is run to fail fast with a meaningful error for ambiguous reconciler definitions.

Since the reconciler validation tests can now live in a _test package, they moved to live next to the primary tests for their respective reconciler.

Tests previously using invalid reconcilers have been corrected or removed.

Resolves #578

### CODE REVIEW

File: testing/reconciler.go [hunk 1]
```diff
@@ -32,6 +32,10 @@ import (
 	"sigs.k8s.io/controller-runtime/pkg/reconcile"
 )
 
+type Validator interface {
+	Validate(ctx context.Context) error
+}
+
```
Comment (mamachanko) [inline testing/reconciler.go:38]: **[thought]:**

I had tested your these changes with my kit, dropping the field `ChildObjectManager` from one of the reconcilers and expecting an error message. However, it still produced the panic described by https://github.com/reconcilerio/runtime/issues/578.

_head scratching..._

Then I realised that I am working with a higher-order reconciler, i.e. `Advice`, which delegates to a `ChildReconciler`. Right now higher-order reconcilers only validate themselves, and not their inner reconcilers. That means the inner validation errors are masked. In fact, we should not even see them at runtime, but panics instead.

Therefore, I think we should export the `Validator` interface from the `reconcilers` package instead. That would allow higher-order reconcilers to sniff their delegate reconcilers for `Validate` and fail fast in case of invalidity.

For example like this with `Advice` only:

```diff
diff --git a/reconcilers/advice.go b/reconcilers/advice.go
index fb083f6..12d223d 100644
--- a/reconcilers/advice.go
+++ b/reconcilers/advice.go
@@ -126,7 +126,11 @@ func (r *Advice[T]) Validate(ctx context.Context) error {
 	if r.Before == nil && r.Around == nil && r.After == nil {
 		return fmt.Errorf("Advice %q must implement at least one of Before, Around or After", r.Name)
 	}
-
+	if v, ok := r.Reconciler.(Validator); ok {
+		if err := v.Validate(ctx); err != nil {
+			return fmt.Errorf("Advice %q has an invalid reconciler: %s", r.Name, err)
+		}
+	}
 	return nil
 }
 
diff --git a/reconcilers/reconcilers.go b/reconcilers/reconcilers.go
index c3fba65..59b38ae 100644
--- a/reconcilers/reconcilers.go
+++ b/reconcilers/reconcilers.go
@@ -39,6 +39,10 @@ type SubReconciler[Type client.Object] interface {
 	Reconcile(ctx context.Context, resource Type) (Result, error)
 }
 
+type Validator interface {
+	Validate(ctx context.Context) error
+}
+
 var (
 	// ErrQuiet are not logged or recorded as events within reconciler.io/runtime.
 	// They are propagated as errors unless otherwise defined.
diff --git a/testing/reconciler.go b/testing/reconciler.go
index e51ad77..0132b85 100644
--- a/testing/reconciler.go
+++ b/testing/reconciler.go
@@ -32,10 +32,6 @@ import (
 	"sigs.k8s.io/controller-runtime/pkg/reconcile"
 )
 
-type Validator interface {
-	Validate(ctx context.Context) error
-}
-
 // ReconcilerTestCase holds a single test case of a reconciler test suite.
 type ReconcilerTestCase struct {
 	// Name is a descriptive name for this test suitable as a first argument to t.Run()
@@ -212,7 +208,7 @@ func (tc *ReconcilerTestCase) Run(t *testing.T, scheme *runtime.Scheme, factory
 	ctx = reconcilers.StashAdditionalConfigs(ctx, configs)
 
 	r := factory(t, tc, expectConfig.Config())
-	if v, ok := r.(Validator); ok {
+	if v, ok := r.(reconcilers.Validator); ok {
 		if err := v.Validate(ctx); err != nil {
 			t.Fatalf("reconciler validation failed: %s", err)
 		}
diff --git a/testing/subreconciler.go b/testing/subreconciler.go
index ecd1009..abc3dcb 100644
--- a/testing/subreconciler.go
+++ b/testing/subreconciler.go
@@ -228,7 +228,7 @@ func (tc *SubReconcilerTestCase[T]) Run(t *testing.T, scheme *runtime.Scheme, fa
 	c := expectConfig.Config()
 
 	r := factory(t, tc, c)
-	if v, ok := r.(Validator); ok {
+	if v, ok := r.(reconcilers.Validator); ok {
 		if err := v.Validate(ctx); err != nil {
 			t.Fatalf("subreconciler validation failed: %s", err)
 		}
```

We would have to extend the same to all higher-order reconcilers

```
❯ rg "\tReconciler SubReconciler\[T" -l
reconcilers/webhook.go
reconcilers/config.go
reconcilers/advice.go
reconcilers/finalizer.go
reconcilers/aggregate.go
reconcilers/flow.go
reconcilers/resource.go
```

I'd be happy to follow-up with a PR, if you prefer.

Comment (scothis) [reply testing/reconciler.go:38]: Good catch regarding nested validation. I'd like to avoid calling into nested validators directory within the validate method because the reconciler name may not be set, which will make it harder to identify where the validation error is actually coming from. For the non-test scenario it would cause the validation to be called n+1 times, where n is depth of the sub reconciler.

Perhaps we can set a value in the context to signal the validation should be recursive and turn it on only for tests. If we want to get fancy with the context, we could also pass a validation error handler via the context and use it to `t.Fatal` for tests and panic for deployed reconcilers.

Comment (mamachanko) [reply testing/reconciler.go:38]: Ok! I like the idea about controlling behaviour via the context and possibly propagating a validation error handler within it. I have recorded https://github.com/reconcilerio/runtime/issues/583 and will work on it.

**Review by mamachanko — APPROVED** [review]
🥳
